### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by beeva-zeusarias** [BatteryAcid/feedback#2]
I have read the following message and need help to configure the add-on.

https://meta.discourse.org/t/oauth2-basic-support/33879/55
https://meta.discourse.org/t/oauth2-basic-support/33879/43

This is possible?

**Comment by BatteryAcid** [comment]
I'll see what I can do, that was a while ago so I'm not sure how helpful I'll be now.  You are working with Keycloak?

**Comment by beeva-zeusarias** [comment]
Yes, I'm working with Keycloak.

My Ouaht2 configuration (discourse) is:

![captura de pantalla de 2017-03-01 16 53 06](https://cloud.githubusercontent.com/assets/16957621/23467938/a98a180a-fe9f-11e6-9896-8f2df32ecebb.png)

Is it ok?

**Comment by BatteryAcid** [comment]
That looks ok to me - what issues are you having?
Also, what version of Keycloak (KC) do you have?

**Comment by beeva-zeusarias** [comment]
My problem is that when I login the screen is blank.

I see this trace in discourse log (/var/www/discourse/log):
production.log
-----------------------------------------------------------
Completed 200 OK in 28ms (Views: 23.3ms | ActiveRecord: 1.0ms)
Started GET "/auth/oauth2_basic" for 62.14.46.178 at 2017-03-01 16:43:58 +0000
(oauth2_basic) Setup endpoint detected, running now.
(oauth2_basic) Request phase initiated.
Started GET "/auth/oauth2_basic/callback?state=abea0a4b205e5668fd4ff4fc7a86a646ab81a9835b02e7d4&code=qMQlqQ4sjpHTOee_Lvr8H_HfwCO2qpaqLPsW-UWqFJw.066f5a57-701a-4bb2-bfdd-70761c5de246" for 62.14.46.178 at 2017-03-01 16:43:58 +0000
(oauth2_basic) Setup endpoint detected, running now.
(oauth2_basic) Callback phase initiated.
Faraday::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed)
/usr/local/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'

Sent mail to email.example.com (146.0ms)
Job exception: hostname "10.7.40.7" does not match the server certificate
-----------------------------------------------------------


My keycloak version is 2.5.1.Final

**Comment by BatteryAcid** [comment]
Looks like you have a certificate issue.  So your configuration may be ok.  Maybe see if there are any options to disable sending emails, to check if that's the issue.  Otherwise it looks like you have to look into your certs.  I can't tell if it is an email issue or an issue between your Keycloak and Discourse servers.

> Faraday::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed)

**Comment by beeva-zeusarias** [comment]
Thank you for your help, I have managed to solve the problem.

I have added the following lines to the app.yml file:

![image](https://cloud.githubusercontent.com/assets/16957621/23500343/fd9056cc-ff2f-11e6-872b-35b8a121acf7.png)

But, I have another problem, because when I close the session in Discourse does not close in Keycloak.

**Comment by BatteryAcid** [comment]
You mean it doesn't log out the user from Keycloak?  Maybe there is a callback option in Discourse to hit the logout API in Keycloak.

**Comment by beeva-zeusarias** [comment]
Thank you for your help.

Greetings.

**Comment by BatteryAcid** [comment]
Ok great, glad I could help.  Closing issue.

**Comment by beeva-zeusarias** [comment]
Hi!

I have another problem. All my oAuth Users have basic privileges.

Can I change this permissions?

**Comment by BatteryAcid** [comment]
Please create new issue on this repository - thanks!
