### ISSUE TITLE
GameLift paid project.

### ISSUE THREAD

**Issue by muxame** [BatteryAcid/feedback#4]
Hello,

I am looking for an experienced and passionate person like you to help with a quick project and hopefully for long-term work business relationship.

It is still not clear for me how to achieve scaleable Texas holdem poker utilizing gamelift.  And I hope you can suggest some ways to achieve that based on your experience. 

Fir example a single server we have contains 120 tables each one has different configuration ( size , blind , speed , etc..). In fame lift are we going to have each table on a separate fleet ? How to scale that with spot instants for poke4 hands that can last for hours without interrupting game play if possible.   If 120 tables each one has separate configuration are we going to have 120 fleets!!?

If you can work on a quick paid project to setup some sample server/ client code (phaser 3) if possible to show case how a turn based poker game can be achieved utilizing Gamelift real-time service this will be great. 

Thanks 
Muhannad

**Comment by BatteryAcid** [comment]
Hello,
There's a lot to unpack there, if you're serious about work please link to your project development team and let me know what your budget is.

Thank you

**Comment by muxame** [comment]
Hello,

Thanks for your reply, sorry for being late responding to your message.

I built this game by myself:- https://www.facebook.com/gaming/play/747969332695877/?source=www_homepage_shortcut
it's called Krytoi Texas Holdem Poker.

I am trying to take it to the next level and be able to add a tournament feature and scale it to handle more players, currently, it's not designed to scale properly or to be as a serverless scalable service ...

Choosing AWS GameLeft is a great option to optimize gameplay and fix scalability issues. maybe will be able to integrate only the poker tournament feature as a start ... 

There are some missing pieces for me with GameLeft, that's why  I require an expert person like you to help with the development process.

I can pay for each delivered task in a step-by-step way, we can start with a simple paid task and see if we can work together 

For example, it's not clear to me how to host each unique poker table on separate fleets/build or not as we have 120 poker tables on each of our poker servers (casino) what will happen if I need to scale? add more tables by activating more fleets or spot instants ...

if you are interested to help I can describe it for you in detail each task and we discuss each issue and solve in step by step bases.

Thanks 
Muhannad

**Comment by BatteryAcid** [comment]
Thanks for the reply, no worries.  I'm just getting back from a short trip myself.

- Are you looking for someone to actually implement the changes or just someone to provide guidance?
- How much work do you think you have to get to serving the game online? I'm assuming this is where you can detail the tasks you were hoping to knock out, at least the first few important items.
- I ask because the hourly rate here is important, which is my preferred method for charging clients.  If I work 20 hours a week, that can add up fast, so think about what range of pay you can afford and let me know.  If I take the job I will also provide an estimate of how long the tasks take.

If you'd like to discuss in a more private channel, please use my discord and DM me:  https://discord.gg/psjbBDvNBK

thank you

**Comment by muxame** [comment]
Hello bro,

Please can you add me to Skype: containerco

Or whatsup : +962788710109

Or you can communicate with me directly via email : ***@***.***

Usually I work using upwork, per project splitting tasks into smaller paid
milestones. but if hourly rate is chosen we can determine the total project
hours then agee on the hour rates...

If you want we can start with a simple 1 week paid milestone that I will
write in details then you can determine the cost for it and you can confirm
if one week is enough to deliver the task or not.... Then from there we can
go forward.

I never worked with gamelift,  and your expertise is too important we can
learn together how to build scalable Texas holdem  game .... below the game
I built for your kind review : made using phaser 3 and .net server


https://fb.gg/play/krytoipokergame/d/1278958052930333/


( It has 3 dedicated servers each server has its own poker rooms "the
tables list at lobby".

I used memcached with AWS aurora db and some load balancing etc..

The issue I am facing that I can't scale tables up and down based on
traffic,  also lots of other issues that's why I am exploring the gamelift
options to introduce matchmaking tournaments at the future and auto scaling
functionality too... hoping to build a more stable game experience to our
users .

Thanks
Muhannad

**Comment by BatteryAcid** [comment]
I'd prefer to use my Discord with private messaging vs Whatsapp or email.  

Can you send me your UpWork profile?
Do you have any links to your existing project code that I can review?
Do you have a repository where this new game code is being managed on Github?

> If you want we can start with a simple 1 week paid milestone that I will
> write in details then you can determine the cost for it and you can confirm
> if one week is enough to deliver the task or not....

Sure, I'd like to see what this would look like, then we can see if it works.
